# Generated by Django 3.1.3 on 2020-11-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0002_vagas'),
    ]

    operations = [
        migrations.CreateModel(
            name='vagass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.IntegerField()),
                ('validacao', models.BooleanField()),
            ],
        ),
    ]
